{
    "has_execution_error": true,
    "execution_output": "Fatal Python error: init_sys_streams: can't initialize sys standard streams\nPython runtime state: core initialized\nOSError: [Errno 9] Bad file descriptor\n\nCurrent thread 0x00000001dcac5c40 (most recent call first):\n  <no Python frame>\n",
    "pred": {
        "error": "malformed_output"
    },
    "gold": {
        "itinerary": [
            {
                "action": "meet",
                "person": "Thomas",
                "start_time": "13:30",
                "end_time": "14:00"
            },
            {
                "action": "meet",
                "person": "Nancy",
                "start_time": "14:45",
                "end_time": "15:00"
            },
            {
                "action": "meet",
                "person": "Brian",
                "start_time": "15:09",
                "end_time": "16:09"
            },
            {
                "action": "meet",
                "person": "Jessica",
                "start_time": "16:30",
                "end_time": "18:30"
            },
            {
                "action": "meet",
                "person": "Mary",
                "start_time": "18:37",
                "end_time": "19:37"
            },
            {
                "action": "meet",
                "person": "Matthew",
                "start_time": "19:52",
                "end_time": "21:52"
            }
        ]
    },
    "status": "Execution error: malformed_output",
    "violated_constraint": {},
    "is_exact_match": false,
    "constraints_satisfied": false,
    "pass_number": 1
}