{
    "has_execution_error": true,
    "execution_output": "Fatal Python error: init_sys_streams: can't initialize sys standard streams\nPython runtime state: core initialized\nOSError: [Errno 9] Bad file descriptor\n\nCurrent thread 0x00000001dcac5c40 (most recent call first):\n  <no Python frame>\n",
    "pred": {
        "error": "malformed_output"
    },
    "gold": {
        "itinerary": [
            {
                "action": "meet",
                "person": "Emily",
                "start_time": "09:15",
                "end_time": "11:15"
            },
            {
                "action": "meet",
                "person": "Linda",
                "start_time": "11:26",
                "end_time": "11:41"
            },
            {
                "action": "meet",
                "person": "Anthony",
                "start_time": "11:52",
                "end_time": "13:37"
            },
            {
                "action": "meet",
                "person": "Helen",
                "start_time": "13:54",
                "end_time": "14:24"
            },
            {
                "action": "meet",
                "person": "Paul",
                "start_time": "14:45",
                "end_time": "16:15"
            },
            {
                "action": "meet",
                "person": "William",
                "start_time": "17:30",
                "end_time": "19:30"
            },
            {
                "action": "meet",
                "person": "Kimberly",
                "start_time": "19:52",
                "end_time": "21:07"
            }
        ]
    },
    "status": "Execution error: malformed_output",
    "violated_constraint": {},
    "is_exact_match": false,
    "constraints_satisfied": false,
    "pass_number": 5
}