{
    "has_execution_error": true,
    "execution_output": "Fatal Python error: init_sys_streams: can't initialize sys standard streams\nPython runtime state: core initialized\nOSError: [Errno 9] Bad file descriptor\n\nCurrent thread 0x00000001dcac5c40 (most recent call first):\n  <no Python frame>\n",
    "pred": {
        "error": "malformed_output"
    },
    "gold": {
        "itinerary": [
            {
                "action": "meet",
                "person": "Nancy",
                "start_time": "09:11",
                "end_time": "10:41"
            },
            {
                "action": "meet",
                "person": "Lisa",
                "start_time": "10:53",
                "end_time": "11:38"
            },
            {
                "action": "meet",
                "person": "Joshua",
                "start_time": "12:00",
                "end_time": "12:15"
            },
            {
                "action": "meet",
                "person": "Andrew",
                "start_time": "12:23",
                "end_time": "13:23"
            },
            {
                "action": "meet",
                "person": "John",
                "start_time": "16:45",
                "end_time": "18:00"
            },
            {
                "action": "meet",
                "person": "Kenneth",
                "start_time": "21:15",
                "end_time": "21:45"
            }
        ]
    },
    "status": "Execution error: malformed_output",
    "violated_constraint": {},
    "is_exact_match": false,
    "constraints_satisfied": false,
    "pass_number": 5
}