{
    "has_execution_error": true,
    "execution_output": "Fatal Python error: init_sys_streams: can't initialize sys standard streams\nPython runtime state: core initialized\nOSError: [Errno 9] Bad file descriptor\n\nCurrent thread 0x00000001dcac5c40 (most recent call first):\n  <no Python frame>\n",
    "pred": {
        "error": "malformed_output"
    },
    "gold": {
        "itinerary": [
            {
                "action": "meet",
                "person": "Sandra",
                "start_time": "09:20",
                "end_time": "09:50"
            },
            {
                "action": "meet",
                "person": "Brian",
                "start_time": "10:15",
                "end_time": "10:45"
            },
            {
                "action": "meet",
                "person": "Stephanie",
                "start_time": "11:03",
                "end_time": "12:18"
            },
            {
                "action": "meet",
                "person": "Helen",
                "start_time": "12:40",
                "end_time": "14:40"
            },
            {
                "action": "meet",
                "person": "Laura",
                "start_time": "14:49",
                "end_time": "16:04"
            },
            {
                "action": "meet",
                "person": "Mary",
                "start_time": "16:45",
                "end_time": "18:45"
            },
            {
                "action": "meet",
                "person": "Deborah",
                "start_time": "19:00",
                "end_time": "20:45"
            }
        ]
    },
    "status": "Execution error: malformed_output",
    "violated_constraint": {},
    "is_exact_match": false,
    "constraints_satisfied": false,
    "pass_number": 2
}