{
    "has_execution_error": true,
    "execution_output": "Fatal Python error: init_sys_streams: can't initialize sys standard streams\nPython runtime state: core initialized\nOSError: [Errno 9] Bad file descriptor\n\nCurrent thread 0x00000001dcac5c40 (most recent call first):\n  <no Python frame>\n",
    "pred": {
        "error": "malformed_output"
    },
    "gold": {
        "itinerary": [
            {
                "action": "meet",
                "person": "Helen",
                "start_time": "09:30",
                "end_time": "10:15"
            },
            {
                "action": "meet",
                "person": "Deborah",
                "start_time": "10:38",
                "end_time": "11:08"
            },
            {
                "action": "meet",
                "person": "Matthew",
                "start_time": "11:35",
                "end_time": "12:20"
            },
            {
                "action": "meet",
                "person": "Rebecca",
                "start_time": "14:45",
                "end_time": "15:15"
            },
            {
                "action": "meet",
                "person": "Joseph",
                "start_time": "15:24",
                "end_time": "17:24"
            },
            {
                "action": "meet",
                "person": "Ronald",
                "start_time": "17:51",
                "end_time": "18:51"
            },
            {
                "action": "meet",
                "person": "Steven",
                "start_time": "20:15",
                "end_time": "22:00"
            }
        ]
    },
    "status": "Execution error: malformed_output",
    "violated_constraint": {},
    "is_exact_match": false,
    "constraints_satisfied": false,
    "pass_number": 3
}