{
    "has_execution_error": true,
    "execution_output": "Traceback (most recent call last):\n  File \"/home/rma336/calendar-planning/source/generated_code_calendar_2025-06-19 03:30:20.py\", line 103, in <module>\n    main()\n  File \"/home/rma336/calendar-planning/source/generated_code_calendar_2025-06-19 03:30:20.py\", line 87, in main\n    meeting_time = find_meeting_time({\n                   ^^^^^^^^^^^^^^^^^^^\n  File \"/home/rma336/calendar-planning/source/generated_code_calendar_2025-06-19 03:30:20.py\", line 16, in find_meeting_time\n    sorted_participants = sorted(participants.items(), key=lambda x: min([t.start for t in x[1]]))\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/rma336/calendar-planning/source/generated_code_calendar_2025-06-19 03:30:20.py\", line 16, in <lambda>\n    sorted_participants = sorted(participants.items(), key=lambda x: min([t.start for t in x[1]]))\n                                                                          ^^^^^^^\nAttributeError: 'datetime.datetime' object has no attribute 'start'",
    "pred": null,
    "gold": {
        "day": "Monday",
        "time_range": "{13:30:14:30}"
    },
    "status": "Error",
    "violated_constraint": {
        "missing_fields": true
    },
    "is_exact_match": false,
    "constraints_satisfied": false,
    "pass_number": 1,
    "timing": {
        "api_call_time": 26.39462971687317,
        "execution_time": 0.012089252471923828,
        "constraint_eval_time": 4.5299530029296875e-06,
        "pred_extract_time": 5.7220458984375e-06,
        "gold_extract_time": 3.0279159545898438e-05,
        "token_count": 0
    }
}