{
    "has_execution_error": true,
    "execution_output": "Fatal Python error: init_sys_streams: can't initialize sys standard streams\nPython runtime state: core initialized\nOSError: [Errno 9] Bad file descriptor\n\nCurrent thread 0x00000001dcac5c40 (most recent call first):\n  <no Python frame>\n",
    "pred": {
        "error": "malformed_output"
    },
    "gold": {
        "itinerary": [
            {
                "action": "meet",
                "person": "William",
                "start_time": "13:15",
                "end_time": "13:45"
            },
            {
                "action": "meet",
                "person": "Robert",
                "start_time": "14:15",
                "end_time": "15:00"
            },
            {
                "action": "meet",
                "person": "Mark",
                "start_time": "15:19",
                "end_time": "16:34"
            },
            {
                "action": "meet",
                "person": "Linda",
                "start_time": "16:57",
                "end_time": "17:27"
            },
            {
                "action": "meet",
                "person": "Elizabeth",
                "start_time": "17:42",
                "end_time": "19:27"
            },
            {
                "action": "meet",
                "person": "Rebecca",
                "start_time": "19:42",
                "end_time": "20:42"
            }
        ]
    },
    "status": "Execution error: malformed_output",
    "violated_constraint": {},
    "is_exact_match": false,
    "constraints_satisfied": false,
    "pass_number": 2
}