{
    "has_execution_error": true,
    "execution_output": "Fatal Python error: init_sys_streams: can't initialize sys standard streams\nPython runtime state: core initialized\nOSError: [Errno 9] Bad file descriptor\n\nCurrent thread 0x00000001dcac5c40 (most recent call first):\n  <no Python frame>\n",
    "pred": {
        "error": "malformed_output"
    },
    "gold": {
        "itinerary": [
            {
                "action": "meet",
                "person": "Robert",
                "start_time": "09:20",
                "end_time": "11:20"
            },
            {
                "action": "meet",
                "person": "Matthew",
                "start_time": "11:37",
                "end_time": "13:07"
            },
            {
                "action": "meet",
                "person": "David",
                "start_time": "13:23",
                "end_time": "14:08"
            },
            {
                "action": "meet",
                "person": "Melissa",
                "start_time": "14:36",
                "end_time": "15:21"
            },
            {
                "action": "meet",
                "person": "Mark",
                "start_time": "15:27",
                "end_time": "16:12"
            },
            {
                "action": "meet",
                "person": "Jessica",
                "start_time": "16:17",
                "end_time": "17:02"
            },
            {
                "action": "meet",
                "person": "Deborah",
                "start_time": "19:00",
                "end_time": "19:45"
            },
            {
                "action": "meet",
                "person": "Karen",
                "start_time": "19:57",
                "end_time": "21:57"
            }
        ]
    },
    "status": "Execution error: malformed_output",
    "violated_constraint": {},
    "is_exact_match": false,
    "constraints_satisfied": false,
    "pass_number": 3
}