{
    "has_execution_error": true,
    "execution_output": "Fatal Python error: init_sys_streams: can't initialize sys standard streams\nPython runtime state: core initialized\nOSError: [Errno 9] Bad file descriptor\n\nCurrent thread 0x00000001dcac5c40 (most recent call first):\n  <no Python frame>\n",
    "pred": {
        "error": "malformed_output"
    },
    "gold": {
        "itinerary": [
            {
                "action": "meet",
                "person": "Jeffrey",
                "start_time": "12:00",
                "end_time": "12:45"
            },
            {
                "action": "meet",
                "person": "Charles",
                "start_time": "13:15",
                "end_time": "15:00"
            },
            {
                "action": "meet",
                "person": "Robert",
                "start_time": "15:18",
                "end_time": "16:48"
            },
            {
                "action": "meet",
                "person": "Kimberly",
                "start_time": "17:00",
                "end_time": "18:15"
            },
            {
                "action": "meet",
                "person": "Karen",
                "start_time": "18:29",
                "end_time": "19:29"
            },
            {
                "action": "meet",
                "person": "Brian",
                "start_time": "19:49",
                "end_time": "20:49"
            },
            {
                "action": "meet",
                "person": "Joshua",
                "start_time": "21:00",
                "end_time": "22:00"
            }
        ]
    },
    "status": "Execution error: malformed_output",
    "violated_constraint": {},
    "is_exact_match": false,
    "constraints_satisfied": false,
    "pass_number": 5
}