{
    "has_execution_error": true,
    "execution_output": "Fatal Python error: init_sys_streams: can't initialize sys standard streams\nPython runtime state: core initialized\nOSError: [Errno 9] Bad file descriptor\n\nCurrent thread 0x00000001dcac5c40 (most recent call first):\n  <no Python frame>\n",
    "pred": {
        "error": "malformed_output"
    },
    "gold": {
        "itinerary": [
            {
                "action": "meet",
                "person": "Melissa",
                "start_time": "09:30",
                "end_time": "10:00"
            },
            {
                "action": "meet",
                "person": "Matthew",
                "start_time": "10:19",
                "end_time": "10:49"
            },
            {
                "action": "meet",
                "person": "Robert",
                "start_time": "11:15",
                "end_time": "13:15"
            },
            {
                "action": "meet",
                "person": "Joseph",
                "start_time": "13:24",
                "end_time": "15:09"
            },
            {
                "action": "meet",
                "person": "Amanda",
                "start_time": "15:25",
                "end_time": "17:10"
            },
            {
                "action": "meet",
                "person": "Karen",
                "start_time": "17:30",
                "end_time": "19:15"
            },
            {
                "action": "meet",
                "person": "Nancy",
                "start_time": "19:31",
                "end_time": "21:16"
            }
        ]
    },
    "status": "Execution error: malformed_output",
    "violated_constraint": {},
    "is_exact_match": false,
    "constraints_satisfied": false,
    "pass_number": 4
}