{
    "has_execution_error": true,
    "execution_output": "Fatal Python error: init_sys_streams: can't initialize sys standard streams\nPython runtime state: core initialized\nOSError: [Errno 9] Bad file descriptor\n\nCurrent thread 0x00000001dcac5c40 (most recent call first):\n  <no Python frame>\n",
    "pred": {
        "error": "malformed_output"
    },
    "gold": {
        "itinerary": [
            {
                "action": "meet",
                "person": "David",
                "start_time": "09:18",
                "end_time": "10:03"
            },
            {
                "action": "meet",
                "person": "Kenneth",
                "start_time": "14:00",
                "end_time": "16:00"
            },
            {
                "action": "meet",
                "person": "Deborah",
                "start_time": "16:09",
                "end_time": "17:39"
            },
            {
                "action": "meet",
                "person": "John",
                "start_time": "17:55",
                "end_time": "18:10"
            },
            {
                "action": "meet",
                "person": "Karen",
                "start_time": "18:31",
                "end_time": "18:46"
            },
            {
                "action": "meet",
                "person": "Charles",
                "start_time": "21:45",
                "end_time": "22:45"
            }
        ]
    },
    "status": "Execution error: malformed_output",
    "violated_constraint": {},
    "is_exact_match": false,
    "constraints_satisfied": false,
    "pass_number": 1
}