/home/hz466/env/lib/python3.12/site-packages/kani/engines/openai/engine.py:113: UserWarning: Could not find a tokenizer for the deepseek-chat model. You may need to update tiktoken.
  warnings.warn(f"Could not find a tokenizer for the {self.model} model. You may need to update tiktoken.")
Running model: DeepSeek-V3
Running task: calendar
Running example: RA
Running example: calendar_scheduling_example_544
Running example: calendar_scheduling_example_398
Running example: calendar_scheduling_example_625
Running example: calendar_scheduling_example_502
Running example: calendar_scheduling_example_798
Running example: calendar_scheduling_example_710
Running example: calendar_scheduling_example_25
Running example: calendar_scheduling_example_493
Running example: calendar_scheduling_example_548
Running example: calendar_scheduling_example_446
Running example: calendar_scheduling_example_786
Running example: calendar_scheduling_example_185
Running example: calendar_scheduling_example_724
Running example: calendar_scheduling_example_819
Running example: calendar_scheduling_example_111
Running example: calendar_scheduling_example_42
Running example: calendar_scheduling_example_476
Running example: calendar_scheduling_example_458
Running example: calendar_scheduling_example_964
Running example: calendar_scheduling_example_629
Running example: calendar_scheduling_example_702
Running example: calendar_scheduling_example_36
Running example: calendar_scheduling_example_244
Running example: calendar_scheduling_example_473
Running example: calendar_scheduling_example_583
OSError: [Errno 28] No space left on device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hz466/calendar-planning/source/generate_smt_input.py", line 102, in <module>
    with open(output_path, "w") as f:
OSError: [Errno 28] No space left on device
